name: Publish Package to GitHub NPM Registry

on: 
  release:
    types: published
    
jobs:
    npm-package:
      runs-on: ubuntu-latest
      permissions: 
        contents: read
        packages: write
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        - name: Setup node
          uses: actions/setup-node@v4
          with:
            node-version: '20.x'
            egistry-url: 'https://npm.pkg.github.com/'
        - name: Install dependencises
          run: npm install 
